# DISCLAIMER: This file was entirely generated by an AI assistant (ChatGPT) based on a user prompt. It may contain errors or incomplete implementations. Please review and test the code thoroughly before using it in production.

import importlib
import inspect
import pkgutil
import types
from typing import Any, Dict, Iterable, Optional, Tuple


def _find_local_commands_package(
    host: Any,
    local_subpackage: str = "commands",
) -> Optional[str]:
    cls = host.__class__

    if not cls.__module__ or cls.__module__ == "__main__":
        return None

    base_module = cls.__module__.rsplit(".", 1)[0]
    candidate_pkg = f"{base_module}.{local_subpackage}"

    try:
        importlib.import_module(candidate_pkg)
        return candidate_pkg
    except ModuleNotFoundError:
        return None


def _iter_cmd_modules(
    package: str,
    module_prefix: str = "_cmd",
) -> Iterable[Tuple[str, Any]]:
    pkg = importlib.import_module(package)

    module_names = []
    for modinfo in pkgutil.iter_modules(pkg.__path__, pkg.__name__ + "."):
        short = modinfo.name.rsplit(".", 1)[-1]
        if short.startswith(module_prefix):
            module_names.append(modinfo.name)

    for module_name in sorted(module_names):
        yield module_name, importlib.import_module(module_name)


def _bind(host: Any, fn: Any) -> Any:
    return types.MethodType(fn, host)


def _mangled_name(cls: type, name: str) -> str:
    return f"_{cls.__name__.lstrip('_')}{name}"


def attach_cmd_functions(
    host: Any,
    *,
    package_map: Optional[Dict[str, str]] = None,
    local_subpackage: str = "commands",
    overwrite: bool = True,
    debug: bool = False,
) -> None:
    """
    Load command functions from local commands package + optional extra packages.

    Conventions:
      - Command modules: _cmd_*.py
      - Regular functions are attached to the instance with their original name
      - Helper functions named '__*' are attached:
          1) literally to the instance
          2) mangled to the class
    """

    def dbg(msg: str) -> None:
        if debug:
            print(f"[registry][debug] {msg}")

    def mangled_name(cls: type, name: str) -> str:
        return f"_{cls.__name__.lstrip('_')}{name}"

    cls = host.__class__
    packages: list[str] = []

    local_pkg = _find_local_commands_package(host, local_subpackage=local_subpackage)
    if local_pkg:
        packages.append(local_pkg)

    if package_map:
        packages.extend(package_map.values())

    dbg(f"Host class: {cls.__name__}, __module__={cls.__module__!r}")
    dbg(f"Packages to load: {packages}")

    for pkg in packages:
        dbg(f"Loading package: {pkg}")

        for module_name, module in _iter_cmd_modules(pkg):
            dbg(f"  Import module: {module_name}")
            dbg(f"  Path: {getattr(module, '__file__', None)}")

            for name, fn in inspect.getmembers(module, inspect.isfunction):
                if fn.__module__ != module.__name__:
                    continue

                is_helper = name.startswith("__") and not name.endswith("__")

                dbg(f"    found function: {name}{inspect.signature(fn)} " f"(helper={is_helper})")

                if is_helper:
                    # mangled = mangled_name(cls, name)
                    mangled = name

                    dbg(f"    helper target names: " f"literal={name!r}, mangled={mangled!r}")

                    if not overwrite:
                        if hasattr(host, name):
                            raise RuntimeError(
                                f"Helper collision on instance: {name} already exists (overwrite=False)"
                            )
                        if hasattr(cls, mangled):
                            raise RuntimeError(
                                f"Helper collision on class: {mangled} already exists (overwrite=False)"
                            )

                    bound = _bind(host, fn)
                    setattr(host, name, bound)
                    setattr(cls, mangled, fn)

                    dbg(
                        f"    helper bound to instance: "
                        f"hasattr(host, {name!r})={hasattr(host, name)}"
                    )
                    try:
                        dbg(f"    helper instance getattr({name!r}) -> {getattr(host, name)}")
                    except Exception as e:
                        dbg(
                            f"    helper instance getattr({name!r}) FAILED: "
                            f"{type(e).__name__}: {e}"
                        )

                    dbg(
                        f"    helper bound to class: "
                        f"hasattr(cls, {mangled!r})={hasattr(cls, mangled)}"
                    )
                    try:
                        dbg(f"    helper class getattr({mangled!r}) -> {getattr(cls, mangled)}")
                    except Exception as e:
                        dbg(
                            f"    helper class getattr({mangled!r}) FAILED: "
                            f"{type(e).__name__}: {e}"
                        )

                    continue

                if (not overwrite) and hasattr(host, name):
                    raise RuntimeError(
                        f"Command collision: {name} already exists (overwrite=False)"
                    )

                bound = _bind(host, fn)
                setattr(host, name, bound)

                dbg(f"    command bound: hasattr(host, {name!r})={hasattr(host, name)}")
                try:
                    dbg(f"    command getattr({name!r}) -> {getattr(host, name)}")
                except Exception as e:
                    dbg(f"    command getattr({name!r}) FAILED: " f"{type(e).__name__}: {e}")

    if debug:
        literal_helpers = sorted(
            n for n in dir(host) if n.startswith("__") and not n.endswith("__")
        )
        mangled_helpers = sorted(
            n for n in dir(cls) if n.startswith(f"_{cls.__name__.lstrip('_')}__")
        )

        dbg(f"Literal helpers on host after attach: {literal_helpers}")
        dbg(f"Mangled helpers on class after attach: {mangled_helpers}")
